### ISSUE TITLE
22/03/2022 update caused Wireless Not Working on Manjaro

### ISSUE THREAD

**Issue by salimp2009** [lwfinger/rtw89#135]
Hi
Currently on Manjaro Gnome with kernel 5.15
I was using your driver on my thinkpad e14 laptop for wireless 
todays update caused to wireless driver disappear . I removed / reinstalled again.
When I search from pacman or Aur it shows installed 

`package version :r170.ff422f1`

When i run inxi -N on terminal it shows;

```
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Realtek RTL8852AE 802.11ax PCIe Wireless Network Adapter
    driver: N/A
```

this is dkms.conf file shows;
```

PACKAGE_NAME="@_PKGBASE@"
PACKAGE_VERSION="@PKGVER@"
BUILT_MODULE_NAME[0]="${PACKAGE_NAME}core"
BUILT_MODULE_NAME[1]="${PACKAGE_NAME}pci"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
DEST_MODULE_LOCATION[0]=/kernel/drivers/net/wireless/realtek/rtw89
DEST_MODULE_LOCATION[1]=/kernel/drivers/net/wireless/realtek/rtw89
AUTOINSTALL=yes
BUILD_EXCLUSIVE_KERNEL="^(4\.[0-9]+\.|5\.[0-9]\.|5\.1[0-5]\.)"
```
and this .install fille

```
post_upgrade() {
  if [[ $(vercmp "1:r0.4dc5371-1" "$2") -eq 1 ]]; then
    # upgraded from epoch 0, kernel <= 5.15
    for i in /usr/lib/modules/*/; do
      i="${i%/*}"
      echo "==> rtw89-dkms-git: depmod ${i}"
      depmod "${i##*/}"
    done
  fi
}
```
